import type { Plugin } from 'vite';
import * as fs from 'fs';
import * as path from 'path';
import { createClient } from './graphql-client';
import { DataFetcher } from './data-fetcher';
import { FileDownloader } from './file-downloader';
import type { BuildTimeData } from './types';

export interface StaticGraphQLPluginOptions {
  endpoint: string;
  appId: string;
  restKey: string;
  masterKey: string;
  projectId?: string;
  outputDir?: string;
  dataFileName?: string;
  filesDir?: string;
}

export function staticGraphQLPlugin(options: StaticGraphQLPluginOptions): Plugin {
  
  console.log('staticGraphQLPlugin', options);
  const {
    endpoint,
    appId,
    restKey,
    masterKey,
    projectId,
    outputDir = 'src/static-data',
    dataFileName = 'build-time-data.json',
    filesDir = 'src/static-data',
  } = options;

  let buildTimeData: BuildTimeData | null = null;

  return {
    name: 'vite-plugin-static-graphql',

    // Run before the build starts
    async buildStart() {
      console.log('\n╔═══════════════════════════════════════════════╗');
      console.log('║   Static GraphQL Data Fetcher Starting...   ║');
      console.log('╚═══════════════════════════════════════════════╝\n');

      try {
        // Create Apollo client
        const client = createClient({
          uri: endpoint,
          appId,
          restKey,
          masterKey,
        });

        // Ensure directories exist
        const resolvedOutputDir = path.resolve(process.cwd(), outputDir);
        const resolvedFilesDir = path.resolve(process.cwd(), filesDir);
        
        if (!fs.existsSync(resolvedOutputDir)) {
          fs.mkdirSync(resolvedOutputDir, { recursive: true });
        }
        if (!fs.existsSync(resolvedFilesDir)) {
          fs.mkdirSync(resolvedFilesDir, { recursive: true });
        }

        // Initialize file downloader
        const fileDownloader = new FileDownloader(resolvedFilesDir);

        // Initialize data fetcher
        const dataFetcher = new DataFetcher(client, fileDownloader, projectId);

        // Fetch all data
        buildTimeData = await dataFetcher.fetchAllData();

        // Write data to JSON file
        const dataFilePath = path.join(resolvedOutputDir, dataFileName);
        fs.writeFileSync(
          dataFilePath,
          JSON.stringify(buildTimeData, null, 2),
          'utf-8'
        );

        console.log(`\n💾 Data saved to: ${dataFilePath}`);
        console.log(`📁 Files saved to: ${resolvedFilesDir}`);

        // Generate TypeScript types
        await generateTypes(resolvedOutputDir);

        console.log('\n╔═══════════════════════════════════════════════╗');
        console.log('║   Static GraphQL Data Fetch Complete! ✨     ║');
        console.log('╚═══════════════════════════════════════════════╝\n');

      } catch (error) {
        console.error('\n❌ Error during static data fetch:', error);
        throw error;
      }
    },

    // Make the data available during development
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        if (req.url === '/api/static-data') {
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify(buildTimeData));
          return;
        }
        next();
      });
    },
  };
}

// Generate TypeScript types for the fetched data
async function generateTypes(outputDir: string) {
      const typesContent = `// Auto-generated types from static GraphQL fetch
// Do not edit this file manually

export interface File {
  __typename?: 'File';
  name: string;
  url: string;
}

export interface Category {
  objectId: string;
  label?: string;
  title?: string;
}

export interface Image {
  objectId: string;
  createdAt: string;
  updatedAt?: string;
  categories?: Category[] | null;
  label?: string | null;
  title?: string | null;
  text?: string | null;
  date?: string | null;
  state?: string | null;
  connected_elements?: Array<{
    value: string;
    label: string;
  }> | null;
  file?: File | null;
}

export interface Person {
  objectId: string;
  createdAt: string;
  updatedAt?: string;
  label?: string | null;
  title?: string | null;
  text?: string | null;
  portrait?: File | null;
}

export interface Entry {
  objectId: string;
  createdAt: string;
  updatedAt?: string;
  categories?: Category[] | null;
  label?: string | null;
  title?: string | null;
  text?: string | null;
  link?: string | null;
  file?: File | null;
  image?: File | null;
  description?: string | null;
  documents?: File[] | null;
}

export interface DownloadedFile {
  objectId: string;
  originalUrl: string;
  localPath: string;
  filename: string;
  type: 'image' | 'document';
}

export interface BuildTimeData {
  images: Image[];
  persons: Person[];
  entries: Entry[];
  downloadedFiles: DownloadedFile[];
}
`;

      const typesFilePath = path.join(outputDir, 'types.ts');
      fs.writeFileSync(typesFilePath, typesContent, 'utf-8');
      console.log(`📝 Types generated: ${typesFilePath}`);
    }
